---
# action.yml
name: 'action-go-template'
description: 'description action-go-template'
author: Inhere
runs:
  using: 'docker'
  # image: 'Dockerfile'
  # image: 'docker://ghcr.io/hi-actions/action-go-template:main'
  image: 'docker://ghcr.io/hi-actions/action-go-template:main'
branding:
  icon: "tag"
  color: "green"
